SASS=sass
TSC=tsc

SCRIPT_DIR=scripts
STYLES_DIR=styles

SCRIPT_OUT_DIR=$(SCRIPT_DIR)/out
STYLES_OUT_DIR=$(STYLES_DIR)/out

SCRIPT_SRCS=index.ts
STYLES_SRCS=style.scss

SCRIPT_OUTPUT=$(SCRIPT_SRCS:%.ts=%.js)
STYLES_OUTPUT=$(STYLES_SRCS:%.scss=%.css)

all: $(SCRIPT_OUT_DIR)/$(SCRIPT_OUTPUT) $(STYLES_OUT_DIR)/$(STYLES_OUTPUT)

$(SCRIPT_OUT_DIR)/$(SCRIPT_OUTPUT): $(SCRIPT_DIR)/$(SCRIPT_SRCS)
	$(TSC) $< --out $@

$(STYLES_OUT_DIR)/$(STYLES_OUTPUT): $(STYLES_DIR)/$(STYLES_SRCS)
	$(SASS) $< $@

run: all
	./run.py

clean:
	rm -rf $(SCRIPT_OUT_DIR) $(STYLES_OUT_DIR)
